### ISSUE TITLE
02-11 Lit on other studies to do with profiles in specific contexts

### ISSUE THREAD

**Issue by rhiaro** [rhiaro/thesis#46]
https://www.aaai.org/ocs/index.php/ICWSM/09/paper/viewFile/156/482
https://www.researchgate.net/profile/Adriana_Manago/publication/222435595_Self-presentation_and_gender_on_MySpace/links/0fcfd50993580d89b0000000.pdf
http://onlinelibrary.wiley.com/doi/10.1111/j.1083-6101.2006.00020.x/full

**Comment by dmitrizagidulin** [comment]
(1st & 3rd link are duplicates)

**Comment by rhiaro** [comment]
Shh I know exactly what I'm doing.

(thanks!)
