### ISSUE TITLE
Something about responsible innovation

### ISSUE THREAD

**Issue by rhiaro** [rhiaro/thesis#78]

**Comment by ghost** [comment]
Who is innovation for?

What are the costs? (Innovation can sometimes waste more time than it saves). Innovations like Bitcoin have big environmental costs. Why are the costs of innovation rarely discussed?

Innovation as spectacle.

Innovation and the bureaucratization of everything. Trust versus audit culture.

**Comment by rhiaro** [comment]
Uuuhhhhhhh.. I have enough material. wontfix, or *maybe* roll into #70
